version: '3.7'

services:
  cableguard_api:
    build: ./cableguard_api
    environment:
      FLASK_APP: wgpt.py
      DATABASE_URL: "mysql+pymysql://wgpt:wgptpassword@db/wgpt"
      TCP_WAIT: "db 3306"
      SKIP_CREATE_DB: 0
    depends_on:
      - db
    volumes:
      - ./cableguard_api/config.py:/wgpt/config.py

  cableguard_cd:
    build: ./cableguard_cd
    environment:
      FLASK_APP: wgpt_cd.py
      DATABASE_URL: "mysql+pymysql://wgpt:wgptpassword@db/wgpt"
      CERT_SSL_CA: "/certs/ca-cert.pem"
      CERT_SSL_CA_KEY: "/certs/ca-key.pem"
      CERT_SSL_SERVER: "/certs/server-cert.pem"
      CERT_SSL_SERVER_KEY: "/certs/server-key.pem"
      CERT_SSL_CHAIN: "/certs/chain-cert.pem"
      TCP_WAIT: "db 3306"
    depends_on:
      - db
    volumes:
      - ./cableguard_cd/config.py:/wgpt/config.py
      - certs:/certs

  webserver:
    build: ./webserver
    environment:
      CERT_SSL_CA: "/certs/ca-cert.pem"
      CERT_SSL_SERVER_KEY: "/certs/server-key.pem"
      CERT_SSL_CHAIN: "/certs/chain-cert.pem"
# HTTP_USER and HTTP_PASSWORD are optional, if left blank access will be open
      HTTP_USER: "admin"
      HTTP_PASSWORD: "password"
    ports:
      - "1443:1443"
      - "2443:2443"
    depends_on:
      - cableguard_api
      - cableguard_cd
    volumes:
      - ./webserver/nginx.conf:/nginx.conf
      - certs:/certs

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: wgpt
      MYSQL_PASSWORD: wgptpassword
      MYSQL_DATABASE: wgpt
    ports:
      - "43306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
    db-data:
    certs:

